language: go

go:
  - 1.x

before_install:
  - go get github.com/mattn/goveralls

script:
  - env GO111MODULE=on go test -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
